import { RefreshCw, Printer, Mail } from "lucide-react"
import useCrudModule from "../../hooks/useCrudModule"
import type { Renewal } from "../../types"
import { fmt, fmtDate } from "../../utils/format"
import StatusBadge from "../../components/ui/StatusBadge"
import DataTable from "../../components/ui/DataTable"
import SearchBar from "../../components/ui/SearchBar"
import StatCard from "../../components/ui/StatCard"
import Modal from "../../components/ui/Modal"
import ConfirmDialog from "../../components/ui/ConfirmDialog"
import EmailDialog from "../../components/ui/EmailDialog"
import { useState, useEffect, useRef } from "react"
import { api } from "../../api/client"

function daysLeft(dateStr: string): number {
  const diff = new Date(dateStr).getTime() - Date.now()
  return Math.ceil(diff / (1000 * 60 * 60 * 24))
}

export default function RenewalsPage() {
  const crud = useCrudModule<Renewal>({ endpoint: "/renewals" })
  const [editData, setEditData] = useState({ newEndDate: "", newPremium: "" })
  const [generating, setGenerating] = useState(false)
  const hasAutoGenerated = useRef(false)
  const [emailDialogOpen, setEmailDialogOpen] = useState(false)
  const [currentRenewalForEmail, setCurrentRenewalForEmail] = useState<number | null>(null)

  const handlePrintPDF = async (id: number) => {
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:3000/api'}/renewals/${id}/pdf`, {
        headers: { Authorization: `Bearer ${localStorage.getItem('token')}` },
      })
      if (!response.ok) throw new Error('Error al generar PDF')
      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `renovacion-${id}.pdf`
      link.click()
      window.URL.revokeObjectURL(url)
      crud.setSuccess('PDF generado exitosamente')
    } catch (error) {
      crud.setError('Error al generar PDF')
    }
  }

  const handleOpenEmailDialog = (id: number) => {
    setCurrentRenewalForEmail(id)
    setEmailDialogOpen(true)
  }

  const handleSendEmail = async (recipients: string[], includeAttachment: boolean) => {
    if (!currentRenewalForEmail) return
    await api.post(`/renewals/${currentRenewalForEmail}/email`, { recipients, includeAttachment })
    crud.setSuccess('Email enviado exitosamente')
    setEmailDialogOpen(false)
    setCurrentRenewalForEmail(null)
  }

  // Auto-generate renewals on mount ONLY ONCE
  useEffect(() => {
    const autoGenerate = async () => {
      // Only run once
      if (hasAutoGenerated.current) return

      // Wait for initial data load
      if (crud.loading) return

      // If no renewals exist, generate them automatically
      if (crud.items.length === 0 && !generating) {
        hasAutoGenerated.current = true
        setGenerating(true)
        try {
          const res = await api.post<{ success: boolean; message: string; data: any }>("/renewals/generate", {})
          if (res.success) {
            await crud.fetchItems()
          }
        } catch (error) {
          console.error("Error auto-generating renewals:", error)
          hasAutoGenerated.current = false // Reset on error to allow retry
        } finally {
          setGenerating(false)
        }
      }
    }

    autoGenerate()
  }, [crud.loading])

  const handleGenerate = async () => {
    if (!confirm("¿Regenerar renovaciones para todas las pólizas próximas a vencer?")) return
    setGenerating(true)
    try {
      const res = await api.post<{ success: boolean; message: string; data: any }>("/renewals/generate", {})
      if (res.success) {
        alert(res.message)
        crud.fetchItems()
      } else {
        alert("Error: " + res.message)
      }
    } catch (error: any) {
      alert("Error al regenerar renovaciones: " + (error.response?.data?.message || error.message))
    } finally {
      setGenerating(false)
    }
  }

  const handleEdit = (item: Renewal) => {
    setEditData({
      newEndDate: item.newEndDate || "",
      newPremium: item.newPremium?.toString() || "",
    })
    crud.openEdit(item)
  }

  const handleSaveEdit = async () => {
    if (!crud.selected) return
    const data: any = {}
    if (editData.newEndDate) data.newEndDate = editData.newEndDate
    if (editData.newPremium) data.newPremium = parseFloat(editData.newPremium)
    await crud.updateItem(crud.selected.id, data)
    setEditData({ newEndDate: "", newPremium: "" })
  }

  const columns = [
    { key: "policy", label: "Póliza", render: (_: any, row: Renewal) => row.policy?.policyNumber || "—" },
    { key: "client", label: "Cliente", render: (_: any, row: Renewal) => row.policy?.client?.name || "—" },
    { key: "insurer", label: "Aseguradora", render: (_: any, row: Renewal) => row.policy?.insurer?.name || "—" },
    { key: "type", label: "Ramo", render: (_: any, row: Renewal) => row.policy?.insuranceType?.name || "—" },
    { key: "originalEndDate", label: "Vencimiento", render: (v: string) => fmtDate(v) },
    { key: "days", label: "Días", render: (_: any, row: Renewal) => {
      const d = daysLeft(row.originalEndDate)
      const color = d < 0 ? "text-red-400" : d <= 30 ? "text-amber-400" : "text-emerald-400"
      return <span className={color}>{d} días</span>
    }},
    { key: "status", label: "Estado", render: (v: string) => <StatusBadge status={v} /> },
  ]

  const pendientes = crud.items.filter(r => r.status === "PENDIENTE").length
  const vencidas = crud.items.filter(r => daysLeft(r.originalEndDate) < 0).length

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-white">Renovaciones</h1>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="px-4 py-2.5 rounded-xl bg-teal-600 hover:bg-teal-500 text-white font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
        >
          <RefreshCw className={`w-4 h-4 ${generating ? 'animate-spin' : ''}`} />
          {generating ? 'Actualizando...' : 'Actualizar Renovaciones'}
        </button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4 mb-6">
        <StatCard title="Total Renovaciones" value={crud.total} icon={RefreshCw} color="teal" />
        <StatCard title="Pendientes" value={pendientes} icon={RefreshCw} color="amber" />
        <StatCard title="Vencidas" value={vencidas} icon={RefreshCw} color="red" />
        <StatCard title="Procesadas" value={crud.items.filter(r => r.status === "PROCESADA").length} icon={RefreshCw} color="emerald" />
      </div>

      <SearchBar value={crud.search} onChange={crud.setSearch} placeholder="Buscar renovación..." />

      {crud.error && <div className="bg-red-500/10 text-red-400 border border-red-500/30 rounded-xl p-3 mb-4 text-sm">{crud.error}</div>}

      <DataTable columns={columns} data={crud.items} loading={crud.loading}
        onView={crud.openView} onEdit={handleEdit} onDelete={crud.askDelete} />

      <Modal isOpen={crud.modal === "view"} onClose={crud.closeModal} title="Detalle de Renovación" size="md">
        {crud.selected && (
          <div className="space-y-3 text-sm">
            <div className="grid grid-cols-2 gap-4">
              <div><span className="text-slate-400">Póliza:</span> <span className="text-white ml-2">{crud.selected.policy?.policyNumber || "—"}</span></div>
              <div><span className="text-slate-400">Estado:</span> <span className="ml-2"><StatusBadge status={crud.selected.status} /></span></div>
              <div><span className="text-slate-400">Cliente:</span> <span className="text-white ml-2">{crud.selected.policy?.client?.name || "—"}</span></div>
              <div><span className="text-slate-400">Aseguradora:</span> <span className="text-white ml-2">{crud.selected.policy?.insurer?.name || "—"}</span></div>
              <div><span className="text-slate-400">Vencimiento:</span> <span className="text-white ml-2">{fmtDate(crud.selected.originalEndDate)}</span></div>
              <div><span className="text-slate-400">Días Restantes:</span> <span className="text-white ml-2">{daysLeft(crud.selected.originalEndDate)} días</span></div>
              {crud.selected.newEndDate && <div><span className="text-slate-400">Nuevo Vencimiento:</span> <span className="text-white ml-2">{fmtDate(crud.selected.newEndDate)}</span></div>}
              {crud.selected.newPremium && <div><span className="text-slate-400">Nueva Prima:</span> <span className="text-white ml-2">{fmt(crud.selected.newPremium)}</span></div>}
            </div>

            <div className="pt-4 border-t border-slate-700">
              <div className="flex gap-2 mb-3">
                <button
                  onClick={() => handlePrintPDF(crud.selected!.id)}
                  className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-sm flex items-center gap-2 transition-colors"
                >
                  <Printer className="w-4 h-4" />
                  Imprimir Aviso
                </button>
                <button
                  onClick={() => handleOpenEmailDialog(crud.selected!.id)}
                  className="px-4 py-2 rounded-xl bg-teal-600 hover:bg-teal-500 text-white text-sm flex items-center gap-2 transition-colors"
                >
                  <Mail className="w-4 h-4" />
                  Enviar Email
                </button>
              </div>

              {crud.selected.status === "PENDIENTE" && (
                <button onClick={() => { crud.patchItem(crud.selected!.id, "notify", {}); }}
                  className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-sm transition-colors">
                  Notificar Cliente
                </button>
              )}
            </div>
          </div>
        )}
      </Modal>

      <Modal isOpen={crud.modal === "edit"} onClose={crud.closeModal} title="Editar Renovación" size="md">
        {crud.selected && crud.selected.status === "PENDIENTE" && (
          <div className="space-y-4">
            <div>
              <label className="block text-sm text-slate-400 mb-2">Nueva Fecha de Vencimiento</label>
              <input
                type="date"
                value={editData.newEndDate}
                onChange={(e) => setEditData({ ...editData, newEndDate: e.target.value })}
                className="w-full px-4 py-2.5 bg-slate-800 border border-slate-700 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-teal-500"
              />
            </div>
            <div>
              <label className="block text-sm text-slate-400 mb-2">Nueva Prima (opcional)</label>
              <input
                type="number"
                step="0.01"
                value={editData.newPremium}
                onChange={(e) => setEditData({ ...editData, newPremium: e.target.value })}
                placeholder="RD$ 0.00"
                className="w-full px-4 py-2.5 bg-slate-800 border border-slate-700 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-teal-500"
              />
            </div>
            <div className="flex gap-2 pt-4">
              <button
                onClick={handleSaveEdit}
                className="flex-1 px-4 py-2.5 rounded-xl bg-teal-600 hover:bg-teal-500 text-white font-medium transition-colors"
              >
                Guardar Cambios
              </button>
              <button
                onClick={crud.closeModal}
                className="flex-1 px-4 py-2.5 rounded-xl bg-slate-700 hover:bg-slate-600 text-white font-medium transition-colors"
              >
                Cancelar
              </button>
            </div>
          </div>
        )}
        {crud.selected && crud.selected.status !== "PENDIENTE" && (
          <div className="text-amber-400 text-sm">
            Solo se pueden editar renovaciones pendientes
          </div>
        )}
      </Modal>

      <ConfirmDialog isOpen={!!crud.deleteTarget} title="Eliminar Renovación"
        message={`¿Está seguro de eliminar la renovación de la póliza "${crud.deleteTarget?.policy?.policyNumber}"?`}
        onConfirm={crud.deleteItem} onCancel={crud.cancelDelete} loading={crud.saving} />

      <EmailDialog
        isOpen={emailDialogOpen}
        onClose={() => {
          setEmailDialogOpen(false)
          setCurrentRenewalForEmail(null)
        }}
        onSend={handleSendEmail}
        recipientOptions={[
          { value: "client", label: "Cliente", description: "Enviar aviso de renovación al cliente" },
          { value: "insurer", label: "Aseguradora", description: "Enviar a la aseguradora" },
          { value: "internal", label: "Interno", description: "Enviar a equipo interno" },
        ]}
        title="Enviar Aviso de Renovación por Email"
        attachmentLabel="Adjuntar aviso (PDF)"
      />
    </div>
  )
}
